Added .env to deployment

diff --git a/.github/workflows/deploy-images.yml b/.github/workflows/deploy-images.yml
--- a/.github/workflows/deploy-images.yml
+++ b/.github/workflows/deploy-images.yml
@@ -78,27 +78,25 @@ jobs:
             "$SSH_USER@$SERVER_IP" << EOF
           set -e
 
-          mkdir -p $DEPLOY_PATH/deploy
-          cd $DEPLOY_PATH
+          mkdir -p $DEPLOY_PATH
+          cd deploy
+
+          # Extract deployment package
+          tar xzf /tmp/deployment.tar.gz
+          rm /tmp/deployment.tar.gz
+
+          # Check if docker-compose file exists
+          if [ ! -f "$DOCKER_COMPOSE_FILE" ]; then
+            echo "ERROR: $DOCKER_COMPOSE_FILE not found!"
+            exit 1
+          fi
 
           ls -a
 
-      #     # Extract deployment package
-      #     tar xzf /tmp/deployment.tar.gz
-      #     rm /tmp/deployment.tar.gz
-
-      #     # Check if docker-compose file exists
-      #     if [ ! -f "$DOCKER_COMPOSE_FILE" ]; then
-      #       echo "ERROR: $DOCKER_COMPOSE_FILE not found!"
-      #       exit 1
-      #     fi
-
-      #     ls deploy
-
-      #     # Copy environment file if exists
-      #     if [ -f .env.production ]; then
-      #       cp .env.production .env
-      #     fi
+          # Copy environment file if exists
+          if [ -f .env.production ]; then
+            cp .env.production .env
+          fi
 
       #     # Clean/repair builder cache and avoid BuildKit flakiness
       #     # sudo systemctl restart docker
